### PR TITLE
Add a function to run build after PR merging

### PR DESCRIPTION
**Pull request by uneme**
Add a function to run build after PR merging.
- Add a function.
- Add a checkbox to control this behavior in the settings menu like a following image.
- Add a xml for updating a database schema.

added_run_build_after_merging

### CODE REVIEW

**Comment by takezoe** [comment]
@uneme Sorry for the very late reply. I've not noticed this pull request. Actually, I noticed this pull request when I found [this article](https://qiita.com/unemen/items/3dcd4885c30b7b5efa9c) on Twitter. Thanks for writing up!

I think this can be run in default and disable option might be unnecessary. What do you think?

**Comment by uneme** [comment]
@takezoe Thank you very much for your reply.

It is better to make this function default.
My opinion is as follows.

1. If we would like to detect ['master broken'](https://about.gitlab.com/blog/2019/09/11/how-to-avoid-broken-master-with-pipelines-for-merge-requests/) state everytime,
then this function should be run default.
2. To run test on every merge, we will not take any risk for that.

In this time, I offered my pull request with the disable option.
It was caused by my defensive personality.

I will make an another pull request that excludes 'disable option'.

**Comment by takezoe** [comment]
Thanks. I'm waiting for a new one. :-) Don't hesitate to ping me if I don't react.

**Comment by uneme** [comment]
I have created a new pull request.
And, it passed tests.

**Pull request closed without merging**
